spring:
  application:
    name: gateway
  cloud:
      gateway:
          discovery:
              locator:
                  enabled: 'true'
                  lower-case-service-id: 'true'   

server:
  port: 8762
eureka:
  client:
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    preferIpAddress: true
    lease-renewal-interval-in-seconds: 3
    lease-expiration-duration-in-seconds: 5
    
---
spring.profiles: monitoring

spring:
   boot:
       admin:
           client:
               url: https://monitoring.sedoo.fr
               auto-deregistration: true   
      
info:
    archive: none

        
endpoints:
    enabled: true
    health:
        enabled: true
management:
    endpoints:
      web:
        exposure:
          include: "*"
    endpoint:
        health:
            show-details: "ALWAYS"
            northstar:
                cacheup: 240
                cachedown: 120   